In [1]:
import pandas as pd
import numpy as np
from sklearn.decomposition import PCA
from sklearn.cluster import KMeans

In [2]:
df = pd.read_csv('merged_dff.csv')

In [4]:
df = df.set_index('SBOEID')

df.shape

(100, 40)

In [5]:
df.head()

,LAST,FIRST,MIDDLE,SUFFIX,add_number,add_apt_no,add_street,add_city,add_zip,dob,...,OCCUPATION,EMPNAME,AMNT,num_contributions,Avg_contributions,max,min,clean_address,latitude,longitude
SBOEID,,,,,,,,,,,,,,,,,,,,,
NY000000000021412753,WILSON-PEREZ,JULIETTE,NaN,NaN,4217,453.0,WHISPERING HLS,CHESTER,10918,19560929,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4217 453 WHISPERING HLS CHESTER 10918,NaN,NaN
NY000000000021351061,DONOHUE,DOROTHY,J,NaN,2607,NaN,WHISPERING HLS,CHESTER,10918,19530614,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2607 WHISPERING HLS CHESTER 10918,NaN,NaN
NY000000000021469254,JOHNSTON,DOUGLAS,C,NaN,1306,NaN,WHISPERING HLS,CHESTER,10918,19760312,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1306 WHISPERING HLS CHESTER 10918,NaN,NaN
NY000000000021542574,KATSCH,MICHELLE,C,NaN,2921,NaN,WHISPERING HLS,CHESTER,10918,19640826,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2921 WHISPERING HLS CHESTER 10918,NaN,NaN
NY000000000021426429,KATSCH,DANIELLE,M,NaN,2921,NaN,WHISPERING HLS,CHESTER,10918,19850412,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2921 WHISPERING HLS CHESTER 10918,NaN,NaN

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 100 entries, NY000000000021412753 to NY000000000021450024
Data columns (total 40 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   LAST               100 non-null    object
 1   FIRST              100 non-null    object
 2   MIDDLE             71 non-null     object
 3   SUFFIX             7 non-null      object
 4   add_number         100 non-null    int64
 5   add_apt_no         5 non-null      float64
 6   add_street         100 non-null    object
 7   add_city           100 non-null    object
 8   add_zip            100 non-null    int64
 9   dob                100 non-null    int64
 10  gender             100 non-null    object
 11  party              100 non-null    object
 12  other_party        0 non-null      float64
 13  COUNTYCODE         100 non-null    int64
 14  ED                 100 non-null    int64
 15  LD                 100 non-null    int64
 16  TOWNCITY           100 non-null    object
 17  WARD               100 non-null    int64
 18  CD                 100 non-null    int64
 19  SD                 100 non-null    int64
 20  AD                 100 non-null    int64
 21  LASTVOTEDDATE      60 non-null     float64
 22  PREVYEARVOTED      0 non-null      float64
 23  REGDATE            100 non-null    int64
 24  VRSOURCE           100 non-null    object
 25  STATUS             100 non-null    object
 26  REASONCODE         100 non-null    object
 27  PURGE_DATE         100 non-null    int64
 28  CONTRID            0 non-null      float64
 29  TOTALAMNT          0 non-null      float64
 30  OCCUPATION         0 non-null      float64
 31  EMPNAME            0 non-null      float64
 32  AMNT               0 non-null      float64
 33  num_contributions  0 non-null      float64
 34  Avg_contributions  0 non-null      float64
 35  max                0 non-null      float64
 36  min                0 non-null      float64
 37  clean_address      100 non-null    object
 38  latitude           66 non-null     float64
 39  longitude          66 non-null     float64
dtypes: float64(15), int64(12), object(13)
memory usage: 32.0+ KB

In [7]:
dff = df[['dob', 'latitude', 'longitude', 'party', 'gender', 'LASTVOTEDDATE']]

In [11]:
dff.dropna().info()

<class 'pandas.core.frame.DataFrame'>
Index: 43 entries, NY000000000021435674 to NY000000000021450024
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   dob            43 non-null     int64
 1   STATUS         43 non-null     object
 2   latitude       43 non-null     float64
 3   longitude      43 non-null     float64
 4   party          43 non-null     object
 5   gender         43 non-null     object
 6   LASTVOTEDDATE  43 non-null     float64
dtypes: float64(3), int64(1), object(3)
memory usage: 2.7+ KB

In [12]:
pca = PCA(n_components=2)
pca.fit(dff)

ValueError: could not convert string to float: 'PURGED'